/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILzReceiver } from "./ILzReceiver";
export type { MockLayerZeroEndpoint } from "./MockLayerZeroEndpoint";
