/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockLayerZeroEndpointInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "lastAdapterParams"
      | "lastDestination"
      | "lastDstChainId"
      | "lastPayload"
      | "lastRefundAddress"
      | "lastValue"
      | "lastZroPaymentAddress"
      | "send"
      | "triggerLzReceive"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "lastAdapterParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastDestination",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastDstChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPayload",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastRefundAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastValue", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastZroPaymentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerLzReceive",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "lastAdapterParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDstChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRefundAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastValue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastZroPaymentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "triggerLzReceive",
    data: BytesLike
  ): Result;
}

export interface MockLayerZeroEndpoint extends BaseContract {
  connect(runner?: ContractRunner | null): MockLayerZeroEndpoint;
  waitForDeployment(): Promise<this>;

  interface: MockLayerZeroEndpointInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lastAdapterParams: TypedContractMethod<[], [string], "view">;

  lastDestination: TypedContractMethod<[], [string], "view">;

  lastDstChainId: TypedContractMethod<[], [bigint], "view">;

  lastPayload: TypedContractMethod<[], [string], "view">;

  lastRefundAddress: TypedContractMethod<[], [string], "view">;

  lastValue: TypedContractMethod<[], [bigint], "view">;

  lastZroPaymentAddress: TypedContractMethod<[], [string], "view">;

  send: TypedContractMethod<
    [
      _dstChainId: BigNumberish,
      _destination: BytesLike,
      _payload: BytesLike,
      _refundAddress: AddressLike,
      _zroPaymentAddress: AddressLike,
      _adapterParams: BytesLike
    ],
    [void],
    "payable"
  >;

  triggerLzReceive: TypedContractMethod<
    [
      receiver: AddressLike,
      srcChainId: BigNumberish,
      srcAddress: BytesLike,
      nonce: BigNumberish,
      payload: BytesLike
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lastAdapterParams"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastDestination"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastDstChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastPayload"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastRefundAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastZroPaymentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "send"
  ): TypedContractMethod<
    [
      _dstChainId: BigNumberish,
      _destination: BytesLike,
      _payload: BytesLike,
      _refundAddress: AddressLike,
      _zroPaymentAddress: AddressLike,
      _adapterParams: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "triggerLzReceive"
  ): TypedContractMethod<
    [
      receiver: AddressLike,
      srcChainId: BigNumberish,
      srcAddress: BytesLike,
      nonce: BigNumberish,
      payload: BytesLike
    ],
    [void],
    "payable"
  >;

  filters: {};
}
