/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ISemaphore {
  export type SemaphoreProofStruct = {
    merkleTreeDepth: BigNumberish;
    merkleTreeRoot: BigNumberish;
    nullifier: BigNumberish;
    message: BigNumberish;
    scope: BigNumberish;
    points: BigNumberish[];
  };

  export type SemaphoreProofStructOutput = [
    merkleTreeDepth: bigint,
    merkleTreeRoot: bigint,
    nullifier: bigint,
    message: bigint,
    scope: bigint,
    points: bigint[]
  ] & {
    merkleTreeDepth: bigint;
    merkleTreeRoot: bigint;
    nullifier: bigint;
    message: bigint;
    scope: bigint;
    points: bigint[];
  };
}

export interface FundingPoolHomeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_STREAM_DURATION_SECONDS"
      | "anonymousContributions"
      | "anonymousNullifierUsed"
      | "campaigns"
      | "claimRefund"
      | "claimRefundAnon"
      | "contribute"
      | "contributeAnon"
      | "contributions"
      | "createCampaign"
      | "daoStartStreaming"
      | "endpoint"
      | "escrowBalance"
      | "finalizeAfterDeadline"
      | "lzReceive"
      | "nextCampaignId"
      | "owner"
      | "processedNonces"
      | "releaseFunds"
      | "semaphoreConfigured"
      | "semaphoreGroupId"
      | "semaphoreVerifier"
      | "setSemaphore"
      | "setTrustedRemote"
      | "startStreaming"
      | "stopStream"
      | "streamClaimable"
      | "streamDurationSeconds"
      | "streamEndTime"
      | "streamRatePerSecond"
      | "streamStartTime"
      | "streamTotalAmount"
      | "streamWithdrawnAmount"
      | "transferOwnership"
      | "trustedRemoteLookup"
      | "withdrawFromStream"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AnonymousContributionReceived"
      | "AnonymousRefundClaimed"
      | "CampaignCreated"
      | "ContributionReceived"
      | "FundsReleased"
      | "RefundClaimed"
      | "StreamStarted"
      | "StreamStopped"
      | "StreamWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_STREAM_DURATION_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "anonymousContributions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "anonymousNullifierUsed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefundAnon",
    values: [BigNumberish, ISemaphore.SemaphoreProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributeAnon",
    values: [BigNumberish, BigNumberish, ISemaphore.SemaphoreProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "daoStartStreaming",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "endpoint", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "escrowBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAfterDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lzReceive",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCampaignId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processedNonces",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "semaphoreConfigured",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "semaphoreGroupId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "semaphoreVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSemaphore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedRemote",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startStreaming",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopStream",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamClaimable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamDurationSeconds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamEndTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamRatePerSecond",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamStartTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamTotalAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streamWithdrawnAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedRemoteLookup",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromStream",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_STREAM_DURATION_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anonymousContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anonymousNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefundAnon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributeAnon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "daoStartStreaming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endpoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "escrowBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAfterDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lzReceive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextCampaignId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "semaphoreConfigured",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "semaphoreGroupId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "semaphoreVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSemaphore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedRemote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startStreaming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stopStream", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "streamClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamDurationSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamRatePerSecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamTotalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamWithdrawnAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedRemoteLookup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromStream",
    data: BytesLike
  ): Result;
}

export namespace AnonymousContributionReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    nullifier: BigNumberish,
    amount: BigNumberish,
    originChainId: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    nullifier: bigint,
    amount: bigint,
    originChainId: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    nullifier: bigint;
    amount: bigint;
    originChainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AnonymousRefundClaimedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    nullifier: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    nullifier: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    nullifier: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    creator: AddressLike,
    goal: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    creator: string,
    goal: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    creator: string;
    goal: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionReceivedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    amount: BigNumberish,
    campaignId: BigNumberish,
    originChainId: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    amount: bigint,
    campaignId: bigint,
    originChainId: bigint
  ];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
    campaignId: bigint;
    originChainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    creator: AddressLike,
    campaignId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    campaignId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    creator: string;
    campaignId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    amount: BigNumberish,
    campaignId: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    amount: bigint,
    campaignId: bigint
  ];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamStartedEvent {
  export type InputTuple = [
    creator: AddressLike,
    campaignId: BigNumberish,
    totalAmount: BigNumberish,
    durationSeconds: BigNumberish,
    ratePerSecond: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    campaignId: bigint,
    totalAmount: bigint,
    durationSeconds: bigint,
    ratePerSecond: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    creator: string;
    campaignId: bigint;
    totalAmount: bigint;
    durationSeconds: bigint;
    ratePerSecond: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamStoppedEvent {
  export type InputTuple = [
    creator: AddressLike,
    campaignId: BigNumberish,
    remainingAmount: BigNumberish,
    totalWithdrawn: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    campaignId: bigint,
    remainingAmount: bigint,
    totalWithdrawn: bigint
  ];
  export interface OutputObject {
    creator: string;
    campaignId: bigint;
    remainingAmount: bigint;
    totalWithdrawn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamWithdrawnEvent {
  export type InputTuple = [
    creator: AddressLike,
    campaignId: BigNumberish,
    amount: BigNumberish,
    totalWithdrawn: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    campaignId: bigint,
    amount: bigint,
    totalWithdrawn: bigint
  ];
  export interface OutputObject {
    creator: string;
    campaignId: bigint;
    amount: bigint;
    totalWithdrawn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FundingPoolHome extends BaseContract {
  connect(runner?: ContractRunner | null): FundingPoolHome;
  waitForDeployment(): Promise<this>;

  interface: FundingPoolHomeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_STREAM_DURATION_SECONDS: TypedContractMethod<[], [bigint], "view">;

  anonymousContributions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  anonymousNullifierUsed: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        creator: string;
        goal: bigint;
        deadline: bigint;
        totalContributed: bigint;
        totalRaised: bigint;
        closed: boolean;
        fundsWithdrawn: boolean;
        fundsReleased: boolean;
        refundEnabled: boolean;
        finalized: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;

  claimRefund: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefundAnon: TypedContractMethod<
    [campaignId: BigNumberish, proof: ISemaphore.SemaphoreProofStruct],
    [void],
    "nonpayable"
  >;

  contribute: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "payable"
  >;

  contributeAnon: TypedContractMethod<
    [
      campaignId: BigNumberish,
      amountWei: BigNumberish,
      proof: ISemaphore.SemaphoreProofStruct
    ],
    [void],
    "payable"
  >;

  contributions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [goalWei: BigNumberish, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  daoStartStreaming: TypedContractMethod<
    [campaignId: BigNumberish, durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  endpoint: TypedContractMethod<[], [string], "view">;

  escrowBalance: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  finalizeAfterDeadline: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  lzReceive: TypedContractMethod<
    [
      _srcChainId: BigNumberish,
      _srcAddress: BytesLike,
      _nonce: BigNumberish,
      _payload: BytesLike
    ],
    [void],
    "payable"
  >;

  nextCampaignId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processedNonces: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  releaseFunds: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  semaphoreConfigured: TypedContractMethod<[], [boolean], "view">;

  semaphoreGroupId: TypedContractMethod<[], [bigint], "view">;

  semaphoreVerifier: TypedContractMethod<[], [string], "view">;

  setSemaphore: TypedContractMethod<
    [_semaphoreVerifier: AddressLike, _groupId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTrustedRemote: TypedContractMethod<
    [srcChainId: BigNumberish, srcAddress: BytesLike],
    [void],
    "nonpayable"
  >;

  startStreaming: TypedContractMethod<
    [campaignId: BigNumberish, durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  stopStream: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  streamClaimable: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  streamDurationSeconds: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  streamEndTime: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  streamRatePerSecond: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  streamStartTime: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  streamTotalAmount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  streamWithdrawnAmount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedRemoteLookup: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  withdrawFromStream: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_STREAM_DURATION_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "anonymousContributions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "anonymousNullifierUsed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        creator: string;
        goal: bigint;
        deadline: bigint;
        totalContributed: bigint;
        totalRaised: bigint;
        closed: boolean;
        fundsWithdrawn: boolean;
        fundsReleased: boolean;
        refundEnabled: boolean;
        finalized: boolean;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefundAnon"
  ): TypedContractMethod<
    [campaignId: BigNumberish, proof: ISemaphore.SemaphoreProofStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "contributeAnon"
  ): TypedContractMethod<
    [
      campaignId: BigNumberish,
      amountWei: BigNumberish,
      proof: ISemaphore.SemaphoreProofStruct
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [goalWei: BigNumberish, deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "daoStartStreaming"
  ): TypedContractMethod<
    [campaignId: BigNumberish, durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "endpoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrowBalance"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeAfterDeadline"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lzReceive"
  ): TypedContractMethod<
    [
      _srcChainId: BigNumberish,
      _srcAddress: BytesLike,
      _nonce: BigNumberish,
      _payload: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "nextCampaignId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processedNonces"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "semaphoreConfigured"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "semaphoreGroupId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "semaphoreVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSemaphore"
  ): TypedContractMethod<
    [_semaphoreVerifier: AddressLike, _groupId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrustedRemote"
  ): TypedContractMethod<
    [srcChainId: BigNumberish, srcAddress: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startStreaming"
  ): TypedContractMethod<
    [campaignId: BigNumberish, durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stopStream"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "streamClaimable"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamDurationSeconds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamEndTime"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamRatePerSecond"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamStartTime"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamTotalAmount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamWithdrawnAmount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedRemoteLookup"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawFromStream"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AnonymousContributionReceived"
  ): TypedContractEvent<
    AnonymousContributionReceivedEvent.InputTuple,
    AnonymousContributionReceivedEvent.OutputTuple,
    AnonymousContributionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "AnonymousRefundClaimed"
  ): TypedContractEvent<
    AnonymousRefundClaimedEvent.InputTuple,
    AnonymousRefundClaimedEvent.OutputTuple,
    AnonymousRefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionReceived"
  ): TypedContractEvent<
    ContributionReceivedEvent.InputTuple,
    ContributionReceivedEvent.OutputTuple,
    ContributionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StreamStarted"
  ): TypedContractEvent<
    StreamStartedEvent.InputTuple,
    StreamStartedEvent.OutputTuple,
    StreamStartedEvent.OutputObject
  >;
  getEvent(
    key: "StreamStopped"
  ): TypedContractEvent<
    StreamStoppedEvent.InputTuple,
    StreamStoppedEvent.OutputTuple,
    StreamStoppedEvent.OutputObject
  >;
  getEvent(
    key: "StreamWithdrawn"
  ): TypedContractEvent<
    StreamWithdrawnEvent.InputTuple,
    StreamWithdrawnEvent.OutputTuple,
    StreamWithdrawnEvent.OutputObject
  >;

  filters: {
    "AnonymousContributionReceived(uint256,uint256,uint256,uint256)": TypedContractEvent<
      AnonymousContributionReceivedEvent.InputTuple,
      AnonymousContributionReceivedEvent.OutputTuple,
      AnonymousContributionReceivedEvent.OutputObject
    >;
    AnonymousContributionReceived: TypedContractEvent<
      AnonymousContributionReceivedEvent.InputTuple,
      AnonymousContributionReceivedEvent.OutputTuple,
      AnonymousContributionReceivedEvent.OutputObject
    >;

    "AnonymousRefundClaimed(uint256,uint256,uint256)": TypedContractEvent<
      AnonymousRefundClaimedEvent.InputTuple,
      AnonymousRefundClaimedEvent.OutputTuple,
      AnonymousRefundClaimedEvent.OutputObject
    >;
    AnonymousRefundClaimed: TypedContractEvent<
      AnonymousRefundClaimedEvent.InputTuple,
      AnonymousRefundClaimedEvent.OutputTuple,
      AnonymousRefundClaimedEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "ContributionReceived(address,uint256,uint256,uint256)": TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;
    ContributionReceived: TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;

    "FundsReleased(address,uint256,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "RefundClaimed(address,uint256,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "StreamStarted(address,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      StreamStartedEvent.InputTuple,
      StreamStartedEvent.OutputTuple,
      StreamStartedEvent.OutputObject
    >;
    StreamStarted: TypedContractEvent<
      StreamStartedEvent.InputTuple,
      StreamStartedEvent.OutputTuple,
      StreamStartedEvent.OutputObject
    >;

    "StreamStopped(address,uint256,uint256,uint256)": TypedContractEvent<
      StreamStoppedEvent.InputTuple,
      StreamStoppedEvent.OutputTuple,
      StreamStoppedEvent.OutputObject
    >;
    StreamStopped: TypedContractEvent<
      StreamStoppedEvent.InputTuple,
      StreamStoppedEvent.OutputTuple,
      StreamStoppedEvent.OutputObject
    >;

    "StreamWithdrawn(address,uint256,uint256,uint256)": TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
    StreamWithdrawn: TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
  };
}
