/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CampaignInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_STREAM_DURATION_SECONDS"
      | "admin"
      | "approveMilestone"
      | "claimRefund"
      | "closed"
      | "contribute"
      | "contributions"
      | "createProposal"
      | "creator"
      | "daoReleaseFunds"
      | "daoReleaseMilestoneFunds"
      | "daoStartStreaming"
      | "deadline"
      | "executeProposal"
      | "finalizeAfterDeadline"
      | "finalized"
      | "fundsReleased"
      | "fundsWithdrawn"
      | "getChainId"
      | "getProposalCount"
      | "goal"
      | "goalReached"
      | "isVerified"
      | "milestoneApprovalWeight"
      | "milestoneVoted"
      | "milestones"
      | "proposalVoted"
      | "proposals"
      | "refund"
      | "refundEnabled"
      | "releaseFunds"
      | "releaseMilestoneFunds"
      | "reportCampaign"
      | "reportCount"
      | "reporters"
      | "setMilestones"
      | "startStreaming"
      | "stopStream"
      | "streamClaimable"
      | "streamDurationSeconds"
      | "streamEndTime"
      | "streamRatePerSecond"
      | "streamStartTime"
      | "streamTotalAmount"
      | "streamWithdrawnAmount"
      | "totalContributed"
      | "totalMilestoneReleased"
      | "totalRaised"
      | "verifyCampaign"
      | "voteProposal"
      | "withdrawFromStream"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignClosed"
      | "CampaignReported"
      | "CampaignVerified"
      | "Contributed"
      | "ContributionReceived"
      | "CrossChainDeposit"
      | "FundsReleased"
      | "MilestoneApproved"
      | "MilestoneCreated"
      | "MilestoneFundsReleased"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "ProposalVoted"
      | "Refund"
      | "RefundClaimed"
      | "StreamStarted"
      | "StreamStopped"
      | "StreamWithdrawn"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_STREAM_DURATION_SECONDS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveMilestone",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "closed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "daoReleaseFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "daoReleaseMilestoneFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "daoStartStreaming",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAfterDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "finalized", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundsReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundsWithdrawn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "goal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "goalReached",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "milestoneApprovalWeight",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "milestoneVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "milestones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseMilestoneFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reportCampaign",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reportCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reporters",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMilestones",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "startStreaming",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stopStream",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streamClaimable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streamDurationSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streamEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streamRatePerSecond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streamStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streamTotalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "streamWithdrawnAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalContributed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMilestoneReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRaised",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCampaign",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromStream",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_STREAM_DURATION_SECONDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "closed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "daoReleaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "daoReleaseMilestoneFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "daoStartStreaming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAfterDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "finalized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundsReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundsWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "goal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "goalReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "milestoneApprovalWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "milestoneVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "milestones", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseMilestoneFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reportCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reporters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startStreaming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stopStream", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "streamClaimable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamDurationSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamRatePerSecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamTotalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streamWithdrawnAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalContributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMilestoneReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromStream",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace CampaignClosedEvent {
  export type InputTuple = [goalReached: boolean];
  export type OutputTuple = [goalReached: boolean];
  export interface OutputObject {
    goalReached: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignReportedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignVerifiedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributedEvent {
  export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [contributor: string, amount: bigint];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionReceivedEvent {
  export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [contributor: string, amount: bigint];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainDepositEvent {
  export type InputTuple = [
    contributor: AddressLike,
    amount: BigNumberish,
    chainId: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    amount: bigint,
    chainId: bigint
  ];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    voter: AddressLike,
    weight: BigNumberish
  ];
  export type OutputTuple = [
    milestoneId: bigint,
    voter: string,
    weight: bigint
  ];
  export interface OutputObject {
    milestoneId: bigint;
    voter: string;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneCreatedEvent {
  export type InputTuple = [
    milestoneId: BigNumberish,
    percentage: BigNumberish
  ];
  export type OutputTuple = [milestoneId: bigint, percentage: bigint];
  export interface OutputObject {
    milestoneId: bigint;
    percentage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneFundsReleasedEvent {
  export type InputTuple = [milestoneId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [milestoneId: bigint, amount: bigint];
  export interface OutputObject {
    milestoneId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [proposalId: BigNumberish, description: string];
  export type OutputTuple = [proposalId: bigint, description: string];
  export interface OutputObject {
    proposalId: bigint;
    description: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalVotedEvent {
  export type InputTuple = [proposalId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [proposalId: bigint, voter: string];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundEvent {
  export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [contributor: string, amount: bigint];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [contributor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [contributor: string, amount: bigint];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamStartedEvent {
  export type InputTuple = [
    creator: AddressLike,
    totalAmount: BigNumberish,
    durationSeconds: BigNumberish,
    ratePerSecond: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    totalAmount: bigint,
    durationSeconds: bigint,
    ratePerSecond: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    creator: string;
    totalAmount: bigint;
    durationSeconds: bigint;
    ratePerSecond: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamStoppedEvent {
  export type InputTuple = [
    creator: AddressLike,
    remainingAmount: BigNumberish,
    totalWithdrawn: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    remainingAmount: bigint,
    totalWithdrawn: bigint
  ];
  export interface OutputObject {
    creator: string;
    remainingAmount: bigint;
    totalWithdrawn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreamWithdrawnEvent {
  export type InputTuple = [
    creator: AddressLike,
    amount: BigNumberish,
    totalWithdrawn: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    amount: bigint,
    totalWithdrawn: bigint
  ];
  export interface OutputObject {
    creator: string;
    amount: bigint;
    totalWithdrawn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Campaign extends BaseContract {
  connect(runner?: ContractRunner | null): Campaign;
  waitForDeployment(): Promise<this>;

  interface: CampaignInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_STREAM_DURATION_SECONDS: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  approveMilestone: TypedContractMethod<
    [milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<[], [void], "nonpayable">;

  closed: TypedContractMethod<[], [boolean], "view">;

  contribute: TypedContractMethod<[], [void], "payable">;

  contributions: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  createProposal: TypedContractMethod<
    [description: string],
    [void],
    "nonpayable"
  >;

  creator: TypedContractMethod<[], [string], "view">;

  daoReleaseFunds: TypedContractMethod<[], [void], "nonpayable">;

  daoReleaseMilestoneFunds: TypedContractMethod<
    [milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  daoStartStreaming: TypedContractMethod<
    [durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  deadline: TypedContractMethod<[], [bigint], "view">;

  executeProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalizeAfterDeadline: TypedContractMethod<[], [void], "nonpayable">;

  finalized: TypedContractMethod<[], [boolean], "view">;

  fundsReleased: TypedContractMethod<[], [boolean], "view">;

  fundsWithdrawn: TypedContractMethod<[], [boolean], "view">;

  getChainId: TypedContractMethod<[], [bigint], "view">;

  getProposalCount: TypedContractMethod<[], [bigint], "view">;

  goal: TypedContractMethod<[], [bigint], "view">;

  goalReached: TypedContractMethod<[], [boolean], "view">;

  isVerified: TypedContractMethod<[], [boolean], "view">;

  milestoneApprovalWeight: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  milestoneVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  milestones: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, boolean] & { percentage: bigint; released: boolean }],
    "view"
  >;

  proposalVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        description: string;
        voteCount: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  refundEnabled: TypedContractMethod<[], [boolean], "view">;

  releaseFunds: TypedContractMethod<[], [void], "nonpayable">;

  releaseMilestoneFunds: TypedContractMethod<
    [milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  reportCampaign: TypedContractMethod<[], [void], "nonpayable">;

  reportCount: TypedContractMethod<[], [bigint], "view">;

  reporters: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setMilestones: TypedContractMethod<
    [percentages: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  startStreaming: TypedContractMethod<
    [durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  stopStream: TypedContractMethod<[], [void], "nonpayable">;

  streamClaimable: TypedContractMethod<[], [bigint], "view">;

  streamDurationSeconds: TypedContractMethod<[], [bigint], "view">;

  streamEndTime: TypedContractMethod<[], [bigint], "view">;

  streamRatePerSecond: TypedContractMethod<[], [bigint], "view">;

  streamStartTime: TypedContractMethod<[], [bigint], "view">;

  streamTotalAmount: TypedContractMethod<[], [bigint], "view">;

  streamWithdrawnAmount: TypedContractMethod<[], [bigint], "view">;

  totalContributed: TypedContractMethod<[], [bigint], "view">;

  totalMilestoneReleased: TypedContractMethod<[], [bigint], "view">;

  totalRaised: TypedContractMethod<[], [bigint], "view">;

  verifyCampaign: TypedContractMethod<[], [void], "nonpayable">;

  voteProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawFromStream: TypedContractMethod<[], [void], "nonpayable">;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_STREAM_DURATION_SECONDS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveMilestone"
  ): TypedContractMethod<[milestoneId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "contributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<[description: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "daoReleaseFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "daoReleaseMilestoneFunds"
  ): TypedContractMethod<[milestoneId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "daoStartStreaming"
  ): TypedContractMethod<[durationSeconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeAfterDeadline"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "fundsReleased"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "fundsWithdrawn"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "goal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "goalReached"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "milestoneApprovalWeight"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "milestoneVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "milestones"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, boolean] & { percentage: bigint; released: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        description: string;
        voteCount: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refundEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseMilestoneFunds"
  ): TypedContractMethod<[milestoneId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportCampaign"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reportCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reporters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setMilestones"
  ): TypedContractMethod<[percentages: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startStreaming"
  ): TypedContractMethod<[durationSeconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stopStream"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "streamClaimable"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamDurationSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamRatePerSecond"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamTotalAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "streamWithdrawnAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalContributed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMilestoneReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRaised"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyCampaign"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFromStream"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CampaignClosed"
  ): TypedContractEvent<
    CampaignClosedEvent.InputTuple,
    CampaignClosedEvent.OutputTuple,
    CampaignClosedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignReported"
  ): TypedContractEvent<
    CampaignReportedEvent.InputTuple,
    CampaignReportedEvent.OutputTuple,
    CampaignReportedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignVerified"
  ): TypedContractEvent<
    CampaignVerifiedEvent.InputTuple,
    CampaignVerifiedEvent.OutputTuple,
    CampaignVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "Contributed"
  ): TypedContractEvent<
    ContributedEvent.InputTuple,
    ContributedEvent.OutputTuple,
    ContributedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionReceived"
  ): TypedContractEvent<
    ContributionReceivedEvent.InputTuple,
    ContributionReceivedEvent.OutputTuple,
    ContributionReceivedEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainDeposit"
  ): TypedContractEvent<
    CrossChainDepositEvent.InputTuple,
    CrossChainDepositEvent.OutputTuple,
    CrossChainDepositEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneCreated"
  ): TypedContractEvent<
    MilestoneCreatedEvent.InputTuple,
    MilestoneCreatedEvent.OutputTuple,
    MilestoneCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneFundsReleased"
  ): TypedContractEvent<
    MilestoneFundsReleasedEvent.InputTuple,
    MilestoneFundsReleasedEvent.OutputTuple,
    MilestoneFundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalVoted"
  ): TypedContractEvent<
    ProposalVotedEvent.InputTuple,
    ProposalVotedEvent.OutputTuple,
    ProposalVotedEvent.OutputObject
  >;
  getEvent(
    key: "Refund"
  ): TypedContractEvent<
    RefundEvent.InputTuple,
    RefundEvent.OutputTuple,
    RefundEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "StreamStarted"
  ): TypedContractEvent<
    StreamStartedEvent.InputTuple,
    StreamStartedEvent.OutputTuple,
    StreamStartedEvent.OutputObject
  >;
  getEvent(
    key: "StreamStopped"
  ): TypedContractEvent<
    StreamStoppedEvent.InputTuple,
    StreamStoppedEvent.OutputTuple,
    StreamStoppedEvent.OutputObject
  >;
  getEvent(
    key: "StreamWithdrawn"
  ): TypedContractEvent<
    StreamWithdrawnEvent.InputTuple,
    StreamWithdrawnEvent.OutputTuple,
    StreamWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "CampaignClosed(bool)": TypedContractEvent<
      CampaignClosedEvent.InputTuple,
      CampaignClosedEvent.OutputTuple,
      CampaignClosedEvent.OutputObject
    >;
    CampaignClosed: TypedContractEvent<
      CampaignClosedEvent.InputTuple,
      CampaignClosedEvent.OutputTuple,
      CampaignClosedEvent.OutputObject
    >;

    "CampaignReported(address)": TypedContractEvent<
      CampaignReportedEvent.InputTuple,
      CampaignReportedEvent.OutputTuple,
      CampaignReportedEvent.OutputObject
    >;
    CampaignReported: TypedContractEvent<
      CampaignReportedEvent.InputTuple,
      CampaignReportedEvent.OutputTuple,
      CampaignReportedEvent.OutputObject
    >;

    "CampaignVerified(address)": TypedContractEvent<
      CampaignVerifiedEvent.InputTuple,
      CampaignVerifiedEvent.OutputTuple,
      CampaignVerifiedEvent.OutputObject
    >;
    CampaignVerified: TypedContractEvent<
      CampaignVerifiedEvent.InputTuple,
      CampaignVerifiedEvent.OutputTuple,
      CampaignVerifiedEvent.OutputObject
    >;

    "Contributed(address,uint256)": TypedContractEvent<
      ContributedEvent.InputTuple,
      ContributedEvent.OutputTuple,
      ContributedEvent.OutputObject
    >;
    Contributed: TypedContractEvent<
      ContributedEvent.InputTuple,
      ContributedEvent.OutputTuple,
      ContributedEvent.OutputObject
    >;

    "ContributionReceived(address,uint256)": TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;
    ContributionReceived: TypedContractEvent<
      ContributionReceivedEvent.InputTuple,
      ContributionReceivedEvent.OutputTuple,
      ContributionReceivedEvent.OutputObject
    >;

    "CrossChainDeposit(address,uint256,uint256)": TypedContractEvent<
      CrossChainDepositEvent.InputTuple,
      CrossChainDepositEvent.OutputTuple,
      CrossChainDepositEvent.OutputObject
    >;
    CrossChainDeposit: TypedContractEvent<
      CrossChainDepositEvent.InputTuple,
      CrossChainDepositEvent.OutputTuple,
      CrossChainDepositEvent.OutputObject
    >;

    "FundsReleased(address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "MilestoneApproved(uint256,address,uint256)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "MilestoneCreated(uint256,uint256)": TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;
    MilestoneCreated: TypedContractEvent<
      MilestoneCreatedEvent.InputTuple,
      MilestoneCreatedEvent.OutputTuple,
      MilestoneCreatedEvent.OutputObject
    >;

    "MilestoneFundsReleased(uint256,uint256)": TypedContractEvent<
      MilestoneFundsReleasedEvent.InputTuple,
      MilestoneFundsReleasedEvent.OutputTuple,
      MilestoneFundsReleasedEvent.OutputObject
    >;
    MilestoneFundsReleased: TypedContractEvent<
      MilestoneFundsReleasedEvent.InputTuple,
      MilestoneFundsReleasedEvent.OutputTuple,
      MilestoneFundsReleasedEvent.OutputObject
    >;

    "ProposalCreated(uint256,string)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(uint256)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalVoted(uint256,address)": TypedContractEvent<
      ProposalVotedEvent.InputTuple,
      ProposalVotedEvent.OutputTuple,
      ProposalVotedEvent.OutputObject
    >;
    ProposalVoted: TypedContractEvent<
      ProposalVotedEvent.InputTuple,
      ProposalVotedEvent.OutputTuple,
      ProposalVotedEvent.OutputObject
    >;

    "Refund(address,uint256)": TypedContractEvent<
      RefundEvent.InputTuple,
      RefundEvent.OutputTuple,
      RefundEvent.OutputObject
    >;
    Refund: TypedContractEvent<
      RefundEvent.InputTuple,
      RefundEvent.OutputTuple,
      RefundEvent.OutputObject
    >;

    "RefundClaimed(address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "StreamStarted(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      StreamStartedEvent.InputTuple,
      StreamStartedEvent.OutputTuple,
      StreamStartedEvent.OutputObject
    >;
    StreamStarted: TypedContractEvent<
      StreamStartedEvent.InputTuple,
      StreamStartedEvent.OutputTuple,
      StreamStartedEvent.OutputObject
    >;

    "StreamStopped(address,uint256,uint256)": TypedContractEvent<
      StreamStoppedEvent.InputTuple,
      StreamStoppedEvent.OutputTuple,
      StreamStoppedEvent.OutputObject
    >;
    StreamStopped: TypedContractEvent<
      StreamStoppedEvent.InputTuple,
      StreamStoppedEvent.OutputTuple,
      StreamStoppedEvent.OutputObject
    >;

    "StreamWithdrawn(address,uint256,uint256)": TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;
    StreamWithdrawn: TypedContractEvent<
      StreamWithdrawnEvent.InputTuple,
      StreamWithdrawnEvent.OutputTuple,
      StreamWithdrawnEvent.OutputObject
    >;

    "Withdrawal(address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
