/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PlatformConfigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addressParams"
      | "boolParams"
      | "owner"
      | "renounceOwnership"
      | "setAddress"
      | "setBool"
      | "setUint"
      | "transferOwnership"
      | "uintParams"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressParamSet"
      | "BoolParamSet"
      | "OwnershipTransferred"
      | "UintParamSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addressParams",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "boolParams",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBool",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uintParams",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "boolParams", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uintParams", data: BytesLike): Result;
}

export namespace AddressParamSetEvent {
  export type InputTuple = [key: BytesLike, value: AddressLike];
  export type OutputTuple = [key: string, value: string];
  export interface OutputObject {
    key: string;
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BoolParamSetEvent {
  export type InputTuple = [key: BytesLike, value: boolean];
  export type OutputTuple = [key: string, value: boolean];
  export interface OutputObject {
    key: string;
    value: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UintParamSetEvent {
  export type InputTuple = [key: BytesLike, value: BigNumberish];
  export type OutputTuple = [key: string, value: bigint];
  export interface OutputObject {
    key: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlatformConfig extends BaseContract {
  connect(runner?: ContractRunner | null): PlatformConfig;
  waitForDeployment(): Promise<this>;

  interface: PlatformConfigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addressParams: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  boolParams: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAddress: TypedContractMethod<
    [key: BytesLike, value: AddressLike],
    [void],
    "nonpayable"
  >;

  setBool: TypedContractMethod<
    [key: BytesLike, value: boolean],
    [void],
    "nonpayable"
  >;

  setUint: TypedContractMethod<
    [key: BytesLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uintParams: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addressParams"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "boolParams"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [key: BytesLike, value: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBool"
  ): TypedContractMethod<
    [key: BytesLike, value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUint"
  ): TypedContractMethod<
    [key: BytesLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uintParams"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "AddressParamSet"
  ): TypedContractEvent<
    AddressParamSetEvent.InputTuple,
    AddressParamSetEvent.OutputTuple,
    AddressParamSetEvent.OutputObject
  >;
  getEvent(
    key: "BoolParamSet"
  ): TypedContractEvent<
    BoolParamSetEvent.InputTuple,
    BoolParamSetEvent.OutputTuple,
    BoolParamSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UintParamSet"
  ): TypedContractEvent<
    UintParamSetEvent.InputTuple,
    UintParamSetEvent.OutputTuple,
    UintParamSetEvent.OutputObject
  >;

  filters: {
    "AddressParamSet(bytes32,address)": TypedContractEvent<
      AddressParamSetEvent.InputTuple,
      AddressParamSetEvent.OutputTuple,
      AddressParamSetEvent.OutputObject
    >;
    AddressParamSet: TypedContractEvent<
      AddressParamSetEvent.InputTuple,
      AddressParamSetEvent.OutputTuple,
      AddressParamSetEvent.OutputObject
    >;

    "BoolParamSet(bytes32,bool)": TypedContractEvent<
      BoolParamSetEvent.InputTuple,
      BoolParamSetEvent.OutputTuple,
      BoolParamSetEvent.OutputObject
    >;
    BoolParamSet: TypedContractEvent<
      BoolParamSetEvent.InputTuple,
      BoolParamSetEvent.OutputTuple,
      BoolParamSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UintParamSet(bytes32,uint256)": TypedContractEvent<
      UintParamSetEvent.InputTuple,
      UintParamSetEvent.OutputTuple,
      UintParamSetEvent.OutputObject
    >;
    UintParamSet: TypedContractEvent<
      UintParamSetEvent.InputTuple,
      UintParamSetEvent.OutputTuple,
      UintParamSetEvent.OutputObject
    >;
  };
}
